### ISSUE TITLE
Fix: Colorado is missing Title 8 (Employment)

### ISSUE THREAD

**Issue by dogweather** [public-law/open-gov-crawlers#180]

**Comment by dogweather** [comment]
```
Converting
  TXT_FILE='title08.txt' to
  XML_FILE='title08.xml'...
Traceback (most recent call last):
  File "/Users/robb/src/PublicLaw/open-gov-crawlers/tmp/sources/CRSDATA20220915/TITLES/../../../../script/crs-txt-to-sgml.py", line 82, in <module>
    cleaned_up = [fix_and_cleanup(line) for line in f.readlines()]
                                                    ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1637: invalid start byte
```

**Comment by dogweather** [comment]
### Invalid Start Byte

* UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82
* UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85
* UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87
* UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4
* UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff
